import type { Brand } from "./brands";

export const INDEX_CANDIDATE_BRANDS: Brand[] = [
  {"id": "us-russell-2000-hut", "seq": 1100000, "added_at": "2026-09-28", "name_ko": "Hut Corp", "name_en": "Hut Corp", "category": "서비스·기업", "logo_png": "/submissions/index-candidates/HUT.png", "has_png": true, "origin": "GLOBAL", "asset_origin": "Russell 2000 공식 도메인 후보", "official_source_page": "https://hut8.com", "sources": [{"provider": "official-domain-discovery", "file": "submissions/index-candidates/HUT.png", "label": "공식 도메인 로고 후보", "source_url": "https://hut8.com"}]},
  {"id": "us-russell-2000-twst", "seq": 1100000, "added_at": "2026-09-28", "name_ko": "Twist Bioscience", "name_en": "Twist Bioscience", "category": "서비스·기업", "logo_png": "/submissions/index-candidates/TWST.png", "has_png": true, "origin": "GLOBAL", "asset_origin": "Russell 2000 공식 도메인 후보", "official_source_page": "https://twistbioscience.com", "sources": [{"provider": "official-domain-discovery", "file": "submissions/index-candidates/TWST.png", "label": "공식 도메인 로고 후보", "source_url": "https://twistbioscience.com"}]},
  {"id": "us-russell-2000-mog-a", "seq": 1100000, "added_at": "2026-09-28", "name_ko": "Moog Inc Class A", "name_en": "Moog Inc Class A", "category": "서비스·기업", "logo_png": "/submissions/index-candidates/MOG_A.webp", "has_png": true, "origin": "GLOBAL", "asset_origin": "Russell 2000 공식 도메인 후보", "official_source_page": "https://moog.com", "sources": [{"provider": "official-domain-discovery", "file": "submissions/index-candidates/MOG_A.webp", "label": "공식 도메인 로고 후보", "source_url": "https://moog.com"}]},
  {"id": "us-russell-2000-umbf", "seq": 1100000, "added_at": "2026-09-28", "name_ko": "Umb Financial", "name_en": "Umb Financial", "category": "서비스·기업", "logo_png": "/submissions/index-candidates/UMBF.png", "has_png": true, "origin": "GLOBAL", "asset_origin": "Russell 2000 공식 도메인 후보", "official_source_page": "https://umb.com", "sources": [{"provider": "official-domain-discovery", "file": "submissions/index-candidates/UMBF.png", "label": "공식 도메인 로고 후보", "source_url": "https://umb.com"}]},
  {"id": "us-russell-2000-vsat", "seq": 1100000, "added_at": "2026-09-28", "name_ko": "Viasat Inc", "name_en": "Viasat Inc", "category": "서비스·기업", "logo_png": "/submissions/index-candidates/VSAT.png", "has_png": true, "origin": "GLOBAL", "asset_origin": "Russell 2000 공식 도메인 후보", "official_source_page": "https://viasat.com", "sources": [{"provider": "official-domain-discovery", "file": "submissions/index-candidates/VSAT.png", "label": "공식 도메인 로고 후보", "source_url": "https://viasat.com"}]},
  {"id": "us-russell-2000-btsg", "seq": 1100000, "added_at": "2026-09-28", "name_ko": "Brightspring Health Services Inc", "name_en": "Brightspring Health Services Inc", "category": "서비스·기업", "logo_png": "/submissions/index-candidates/BTSG.png", "has_png": true, "origin": "GLOBAL", "asset_origin": "Russell 2000 공식 도메인 후보", "official_source_page": "https://brightspringhealth.com", "sources": [{"provider": "official-domain-discovery", "file": "submissions/index-candidates/BTSG.png", "label": "공식 도메인 로고 후보", "source_url": "https://brightspringhealth.com"}]},
  {"id": "us-russell-2000-krys", "seq": 1100000, "added_at": "2026-09-28", "name_ko": "Krystal Biotech", "name_en": "Krystal Biotech", "category": "서비스·기업", "logo_png": "/submissions/index-candidates/KRYS.png", "has_png": true, "origin": "GLOBAL", "asset_origin": "Russell 2000 공식 도메인 후보", "official_source_page": "https://krystalbio.com", "sources": [{"provider": "official-domain-discovery", "file": "submissions/index-candidates/KRYS.png", "label": "공식 도메인 로고 후보", "source_url": "https://krystalbio.com"}]},
  {"id": "us-russell-2000-ctre", "seq": 1100000, "added_at": "2026-09-28", "name_ko": "Caretrust Reit", "name_en": "Caretrust Reit", "category": "서비스·기업", "logo_png": "/submissions/index-candidates/CTRE.svg", "has_png": true, "origin": "GLOBAL", "asset_origin": "Russell 2000 공식 도메인 후보", "official_source_page": "https://caretrustreit.com", "sources": [{"provider": "official-domain-discovery", "file": "submissions/index-candidates/CTRE.svg", "label": "공식 도메인 로고 후보", "source_url": "https://caretrustreit.com"}]},
  {"id": "us-russell-2000-gkos", "seq": 1100000, "added_at": "2026-09-28", "name_ko": "Glaukos", "name_en": "Glaukos", "category": "서비스·기업", "logo_png": "/submissions/index-candidates/GKOS.png", "has_png": true, "origin": "GLOBAL", "asset_origin": "Russell 2000 공식 도메인 후보", "official_source_page": "https://glaukos.com", "sources": [{"provider": "official-domain-discovery", "file": "submissions/index-candidates/GKOS.png", "label": "공식 도메인 로고 후보", "source_url": "https://glaukos.com"}]},
  {"id": "us-russell-2000-cytk", "seq": 1100000, "added_at": "2026-09-28", "name_ko": "Cytokinetics", "name_en": "Cytokinetics", "category": "서비스·기업", "logo_png": "/submissions/index-candidates/CYTK.png", "has_png": true, "origin": "GLOBAL", "asset_origin": "Russell 2000 공식 도메인 후보", "official_source_page": "https://cytokinetics.com", "sources": [{"provider": "official-domain-discovery", "file": "submissions/index-candidates/CYTK.png", "label": "공식 도메인 로고 후보", "source_url": "https://cytokinetics.com"}]},
  {"id": "us-russell-2000-onb", "seq": 1100000, "added_at": "2026-09-28", "name_ko": "Old National Bancorp", "name_en": "Old National Bancorp", "category": "서비스·기업", "logo_png": "/submissions/index-candidates/ONB.png", "has_png": true, "origin": "GLOBAL", "asset_origin": "Russell 2000 공식 도메인 후보", "official_source_page": "https://oldnational.com", "sources": [{"provider": "official-domain-discovery", "file": "submissions/index-candidates/ONB.png", "label": "공식 도메인 로고 후보", "source_url": "https://oldnational.com"}]},
  {"id": "us-russell-2000-fcfs", "seq": 1100000, "added_at": "2026-09-28", "name_ko": "Firstcash Holdings Inc", "name_en": "Firstcash Holdings Inc", "category": "서비스·기업", "logo_png": "/submissions/index-candidates/FCFS.png", "has_png": true, "origin": "GLOBAL", "asset_origin": "Russell 2000 공식 도메인 후보", "official_source_page": "https://firstcash.com", "sources": [{"provider": "official-domain-discovery", "file": "submissions/index-candidates/FCFS.png", "label": "공식 도메인 로고 후보", "source_url": "https://firstcash.com"}]},
  {"id": "us-russell-2000-riot", "seq": 1100000, "added_at": "2026-09-28", "name_ko": "Riot Platforms", "name_en": "Riot Platforms", "category": "서비스·기업", "logo_png": "/submissions/index-candidates/RIOT.webp", "has_png": true, "origin": "GLOBAL", "asset_origin": "Russell 2000 공식 도메인 후보", "official_source_page": "https://riotplatforms.com", "sources": [{"provider": "official-domain-discovery", "file": "submissions/index-candidates/RIOT.webp", "label": "공식 도메인 로고 후보", "source_url": "https://riotplatforms.com"}]},
  {"id": "us-russell-2000-tgtx", "seq": 1100000, "added_at": "2026-09-28", "name_ko": "Tg Therapeutics", "name_en": "Tg Therapeutics", "category": "서비스·기업", "logo_png": "/submissions/index-candidates/TGTX.svg", "has_png": true, "origin": "GLOBAL", "asset_origin": "Russell 2000 공식 도메인 후보", "official_source_page": "https://tgtherapeutics.com", "sources": [{"provider": "official-domain-discovery", "file": "submissions/index-candidates/TGTX.svg", "label": "공식 도메인 로고 후보", "source_url": "https://tgtherapeutics.com"}]},
  {"id": "us-russell-2000-rhp", "seq": 1100000, "added_at": "2026-09-28", "name_ko": "Ryman Hospitality Properties Reit", "name_en": "Ryman Hospitality Properties Reit", "category": "서비스·기업", "logo_png": "/submissions/index-candidates/RHP.png", "has_png": true, "origin": "GLOBAL", "asset_origin": "Russell 2000 공식 도메인 후보", "official_source_page": "https://rhp.com", "sources": [{"provider": "official-domain-discovery", "file": "submissions/index-candidates/RHP.png", "label": "공식 도메인 로고 후보", "source_url": "https://rhp.com"}]},
  {"id": "us-russell-2000-ssrm", "seq": 1100000, "added_at": "2026-09-28", "name_ko": "Ssr Mining", "name_en": "Ssr Mining", "category": "서비스·기업", "logo_png": "/submissions/index-candidates/SSRM.png", "has_png": true, "origin": "GLOBAL", "asset_origin": "Russell 2000 공식 도메인 후보", "official_source_page": "https://ssrmining.com", "sources": [{"provider": "official-domain-discovery", "file": "submissions/index-candidates/SSRM.png", "label": "공식 도메인 로고 후보", "source_url": "https://ssrmining.com"}]},
  {"id": "us-russell-2000-pcvx", "seq": 1100000, "added_at": "2026-09-28", "name_ko": "Vaxcyte", "name_en": "Vaxcyte", "category": "서비스·기업", "logo_png": "/submissions/index-candidates/PCVX.png", "has_png": true, "origin": "GLOBAL", "asset_origin": "Russell 2000 공식 도메인 후보", "official_source_page": "https://vaxcyte.com", "sources": [{"provider": "official-domain-discovery", "file": "submissions/index-candidates/PCVX.png", "label": "공식 도메인 로고 후보", "source_url": "https://vaxcyte.com"}]},
  {"id": "us-russell-2000-mxl", "seq": 1100000, "added_at": "2026-09-28", "name_ko": "Maxlinear", "name_en": "Maxlinear", "category": "서비스·기업", "logo_png": "/submissions/index-candidates/MXL.png", "has_png": true, "origin": "GLOBAL", "asset_origin": "Russell 2000 공식 도메인 후보", "official_source_page": "https://maxlinear.com", "sources": [{"provider": "official-domain-discovery", "file": "submissions/index-candidates/MXL.png", "label": "공식 도메인 로고 후보", "source_url": "https://maxlinear.com"}]},
  {"id": "us-russell-2000-slab", "seq": 1100000, "added_at": "2026-09-28", "name_ko": "Silicon Laboratories", "name_en": "Silicon Laboratories", "category": "서비스·기업", "logo_png": "/submissions/index-candidates/SLAB.svg", "has_png": true, "origin": "GLOBAL", "asset_origin": "Russell 2000 공식 도메인 후보", "official_source_page": "https://slab.com", "sources": [{"provider": "official-domain-discovery", "file": "submissions/index-candidates/SLAB.svg", "label": "공식 도메인 로고 후보", "source_url": "https://slab.com"}]},
  {"id": "us-russell-2000-aca", "seq": 1100000, "added_at": "2026-09-28", "name_ko": "Arcosa", "name_en": "Arcosa", "category": "서비스·기업", "logo_png": "/submissions/index-candidates/ACA.png", "has_png": true, "origin": "GLOBAL", "asset_origin": "Russell 2000 공식 도메인 후보", "official_source_page": "https://arcosa.com", "sources": [{"provider": "official-domain-discovery", "file": "submissions/index-candidates/ACA.png", "label": "공식 도메인 로고 후보", "source_url": "https://arcosa.com"}]},
];
