import type { Brand } from "./brands";

export const INDEX_CANDIDATE_BRANDS: Brand[] = [
  {"id": "us-russell-2000-twst", "seq": 1100000, "added_at": "2026-09-28", "name_ko": "Twist Bioscience", "name_en": "Twist Bioscience", "category": "서비스·기업", "logo_png": "/submissions/index-candidates/TWST.png", "has_png": true, "logo_svg": null, "has_svg": false, "origin": "GLOBAL", "asset_origin": "Russell 2000 공식 도메인 검수 후보", "official_source_page": "https://twistbioscience.com"},
  {"id": "us-russell-2000-mog-a", "seq": 1100000, "added_at": "2026-09-28", "name_ko": "Moog Inc Class A", "name_en": "Moog Inc Class A", "category": "서비스·기업", "logo_png": "/submissions/index-candidates/MOG_A.webp", "has_png": true, "logo_svg": null, "has_svg": false, "origin": "GLOBAL", "asset_origin": "Russell 2000 공식 도메인 검수 후보", "official_source_page": "https://moog.com"},
  {"id": "us-russell-2000-vsat", "seq": 1100000, "added_at": "2026-09-28", "name_ko": "Viasat Inc", "name_en": "Viasat Inc", "category": "서비스·기업", "logo_png": "/submissions/index-candidates/VSAT.png", "has_png": true, "logo_svg": null, "has_svg": false, "origin": "GLOBAL", "asset_origin": "Russell 2000 공식 도메인 검수 후보", "official_source_page": "https://viasat.com"},
  {"id": "us-russell-2000-ctre", "seq": 1100000, "added_at": "2026-09-28", "name_ko": "Caretrust Reit", "name_en": "Caretrust Reit", "category": "서비스·기업", "logo_png": "/submissions/index-candidates/CTRE.svg", "has_png": false, "logo_svg": "/submissions/index-candidates/CTRE.svg", "has_svg": true, "origin": "GLOBAL", "asset_origin": "Russell 2000 공식 도메인 검수 후보", "official_source_page": "https://caretrustreit.com"},
  {"id": "us-russell-2000-cytk", "seq": 1100000, "added_at": "2026-09-28", "name_ko": "Cytokinetics", "name_en": "Cytokinetics", "category": "서비스·기업", "logo_png": "/submissions/index-candidates/CYTK.png", "has_png": true, "logo_svg": null, "has_svg": false, "origin": "GLOBAL", "asset_origin": "Russell 2000 공식 도메인 검수 후보", "official_source_page": "https://cytokinetics.com"},
  {"id": "us-russell-2000-tgtx", "seq": 1100000, "added_at": "2026-09-28", "name_ko": "Tg Therapeutics", "name_en": "Tg Therapeutics", "category": "서비스·기업", "logo_png": "/submissions/index-candidates/TGTX.svg", "has_png": false, "logo_svg": "/submissions/index-candidates/TGTX.svg", "has_svg": true, "origin": "GLOBAL", "asset_origin": "Russell 2000 공식 도메인 검수 후보", "official_source_page": "https://tgtherapeutics.com"},
  {"id": "us-russell-2000-slab", "seq": 1100000, "added_at": "2026-09-28", "name_ko": "Silicon Laboratories", "name_en": "Silicon Laboratories", "category": "서비스·기업", "logo_png": "/submissions/index-candidates/SLAB.svg", "has_png": false, "logo_svg": "/submissions/index-candidates/SLAB.svg", "has_svg": true, "origin": "GLOBAL", "asset_origin": "Russell 2000 공식 도메인 검수 후보", "official_source_page": "https://slab.com"},
];
