import { trafficAdmin,trafficDb } from '@/lib/traffic-db';
export const dynamic='force-dynamic';
const reply=(body:unknown,status=200)=>Response.json(body,{status,headers:{'Cache-Control':'no-store'}});
export async function GET(request:Request){try{const id=new URL(request.url).searchParams.get('id')||'';if(!/^[\p{L}\p{N}._-]{1,200}$/u.test(id))return reply({error:'로고를 확인해 주세요.'},400);const r=await trafficDb().query("SELECT v.id,v.brand_id,v.assets,v.asset_manifest,v.label,v.version_kind,v.introduced_year,v.retired_year,v.source_url,v.source_note,v.review_status,v.is_current,v.observed_at FROM semologo.logo_versions v JOIN semologo.logo_posts p ON p.id=v.brand_id WHERE v.brand_id=$1 AND p.status='published' AND v.review_status<>'rejected' ORDER BY v.is_current DESC,v.observed_at DESC",[id]);return reply({versions:r.rows});}catch{return reply({error:'로고 이력을 불러오지 못했어요.'},503);}}
export async function PATCH(request:Request){try{if(!await trafficAdmin(request))return reply({error:'관리자 로그인이 필요해요.'},403);let b;try{b=await request.json();}catch{return reply({error:'입력한 내용을 확인해 주세요.'},400);}
 const year=(v:unknown)=>v===null||v===''?null:typeof v==='number'&&Number.isInteger(v)&&v>=1&&v<=new Date().getFullYear()?v:undefined;
 const start=year(b.introduced_year),end=year(b.retired_year);let source:URL|undefined;try{if(b.source_url){if(typeof b.source_url!=='string'||b.source_url.length>2000)throw Error('source');source=new URL(b.source_url);}}catch{return reply({error:'출처 주소를 확인해 주세요.'},400);}
 if(typeof b.id!=='string'||b.id.length>300||typeof b.label!=='string'||!b.label.trim()||b.label.length>120||start===undefined||end===undefined||(start!==null&&end!==null&&end<start)||(source&&(source.protocol!=='https:'||source.username||source.password))||((start!==null||end!==null)&&!source)||!['legacy_import','asset_revision','brand_redesign'].includes(b.version_kind))return reply({error:'연도·버전 이름과 근거가 되는 출처를 확인해 주세요.'},400);
 const r=await trafficDb().query("UPDATE semologo.logo_versions SET label=$2,introduced_year=$3,retired_year=$4,source_url=$5,source_note=$6,version_kind=$7 WHERE id=$1 RETURNING id",[b.id,b.label.trim(),start,end,source?.href||null,typeof b.source_note==='string'?b.source_note.slice(0,1000):null,b.version_kind]);return r.rowCount===1?reply({ok:true}):reply({error:'버전을 찾지 못했어요.'},404);
 }catch{return reply({error:'로고 이력을 저장하지 못했어요.'},503);}}
