"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import Header from "./Header";
import { collection, addDoc, Timestamp } from "firebase/firestore";
import { getClientDb } from "@/lib/firebase";
import { trackEvent } from "@/lib/analytics";
export default function EnglishRequestPage() {
  const [name,setName]=useState("");const [website,setWebsite]=useState("");const [note,setNote]=useState("");const [status,setStatus]=useState("idle");
  async function submit(e:React.FormEvent){e.preventDefault();if(!name.trim())return;setStatus("sending");try{await addDoc(collection(getClientDb(),"logo_requests_public"),{brand_name:name.trim(),website:website.trim(),note:note.trim(),votes:0,status:"pending",created_at:Timestamp.now()});const fd=new FormData();fd.set("brand_name",`[Logo request] ${name}`);fd.set("logo_url",website);fd.set("memo",note);fetch("https://ai.vibers.co.kr/api/logo-submit",{method:"POST",body:fd}).catch(()=>{});trackEvent("request_submitted",{has_website:Boolean(website),has_note:Boolean(note)});setStatus("done");setName("");setWebsite("");setNote("");}catch{setStatus("error");}}
  return <div className="min-h-screen" style={{background:"var(--bg)"}}><Header/><main className="mx-auto max-w-[720px] px-4 py-12"><Link href="/en/" className="text-sm text-gray-500">← SemoLogo home</Link><h1 className="mt-6 text-3xl font-black">Request a logo</h1><p className="mt-2 text-sm text-gray-500">Tell us which brand should be added. Other visitors can vote for requests.</p><div className="mt-8 rounded-2xl border bg-white p-6"><h2 className="text-lg font-bold">New logo request</h2>{status === "done" ? <div className="py-10 text-center"><p className="text-4xl">🎉</p><p className="mt-3 font-bold">Request received</p><p className="mt-2 text-sm text-gray-500">We’ll review it and add it when possible.</p><button onClick={()=>setStatus("idle")} className="mt-5 rounded-full border px-5 py-2 text-sm">Request another</button></div> : <form onSubmit={submit} className="mt-5 flex flex-col gap-4"><label className="text-sm font-semibold">Brand name<input required value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Acme" className="mt-2 w-full rounded-lg border p-3 font-normal"/></label><label className="text-sm font-semibold">Official website <span className="font-normal text-gray-500">(optional)</span><input type="url" value={website} onChange={e=>setWebsite(e.target.value)} placeholder="https://example.com" className="mt-2 w-full rounded-lg border p-3 font-normal"/></label><label className="text-sm font-semibold">Notes <span className="font-normal text-gray-500">(optional)</span><textarea value={note} onChange={e=>setNote(e.target.value)} rows={3} placeholder="Which logo or version do you need?" className="mt-2 w-full rounded-lg border p-3 font-normal"/></label>{status === "error"&&<p role="alert" className="text-sm text-red-600">Couldn’t save this request. Please try again.</p>}<button disabled={status==="sending"||!name.trim()} className="rounded-xl bg-black py-3 text-sm font-bold text-white disabled:opacity-40">{status==="sending"?"Sending…":"Send request"}</button></form>}</div></main></div>;
}
