'use client';
import {useEffect,useState} from 'react';
import {getClientAuth} from '@/lib/firebase';
import {CDN} from '@/lib/cdn';
type Version={id:string;brand_id:string;label:string;introduced_year:number|null;retired_year:number|null;version_kind:string;source_url:string|null;source_note:string|null;is_current:boolean;observed_at:string;review_status:string;assets:Record<string,unknown>};
function fileUrl(v:Version,kind:'png'|'svg'){
 if(v.review_status!=='verified')return null;
 const a=v.assets;const file=kind==='png'?a.preview_png||a.logo_png:a.svg_transparent||a.logo_svg;
 if(typeof file==='string'){if(file.startsWith(CDN+'/'))return file;if(file.startsWith('/submissions/')&&!file.includes('..'))return file;if(!file.includes('..')&&/^(?:[\w-]+\/)*[\w.-]+\.(png|svg)$/.test(file))return `${CDN}/${v.brand_id}/${file}`;}
 return a[kind==='png'?'has_png':'has_svg']?`${CDN}/${v.brand_id}/logo.${kind}`:null;
}
export default function LogoVersionHistory({brandId,isAdmin}:{brandId:string;isAdmin:boolean}){
 const [versions,setVersions]=useState<Version[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true),[editing,setEditing]=useState<Version|null>(null),[saving,setSaving]=useState(false);
 async function load(signal?:AbortSignal){try{const r=await fetch(`/api/logo-versions/?id=${encodeURIComponent(brandId)}`,{cache:'no-store',signal});const d=await r.json();if(!r.ok)throw Error(d.error);if(!signal?.aborted){setVersions(d.versions);setError('');}}catch(e){if(!signal?.aborted)setError(e instanceof Error?e.message:'이력을 불러오지 못했어요.');}finally{if(!signal?.aborted)setLoading(false);}}
 useEffect(()=>{const c=new AbortController();setLoading(true);void load(c.signal);return()=>c.abort();},[brandId]);
 async function save(){if(!editing)return;setSaving(true);try{const token=await getClientAuth().currentUser?.getIdToken();const r=await fetch('/api/logo-versions/',{method:'PATCH',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify(editing)});const d=await r.json();if(!r.ok)throw Error(d.error);setEditing(null);await load();}catch(e){setError(e instanceof Error?e.message:'저장하지 못했어요.');}finally{setSaving(false);}}
 return <section style={{margin:'18px 0',padding:14,border:'1px solid #e4e4e7',borderRadius:10}} aria-label="로고 아카이브"><details><summary style={{fontSize:13,fontWeight:700,cursor:'pointer'}}>로고 아카이브 · {versions.find(v=>v.is_current)?.introduced_year || '도입 연도 미확인'}</summary><p style={{fontSize:11,color:'#71717a',margin:'5px 0 10px'}}>확인된 도입 연도와 수집 이력을 함께 보관해요. 수집 날짜는 로고가 만들어진 날짜와 달라요.</p>
 {loading?<p style={{fontSize:12}}>이력을 불러오는 중이에요.</p>:error?<p role="alert" style={{fontSize:12,color:'#dc2626'}}>{error} <button onClick={()=>void load()}>다시 불러오기</button></p>:!versions.length?<p style={{fontSize:12,color:'#71717a'}}>확인된 이력이 없어요.</p>:<div style={{display:'grid',gap:10}}>{versions.map(v=>{const png=fileUrl(v,'png'),svg=fileUrl(v,'svg');return <article key={v.id} style={{borderTop:'1px solid #f0f0f2',paddingTop:10,display:'flex',gap:12,alignItems:'center',flexWrap:'wrap'}}>{(png||svg)&&<img src={png||svg!} alt="" style={{width:90,height:50,objectFit:'contain',background:v.assets.light?'#18181b':'#fff'}} onError={e=>{e.currentTarget.style.display='none';}}/>}<div style={{flex:1,minWidth:160}}><b style={{fontSize:12}}>{v.introduced_year?`${v.introduced_year}${v.retired_year?`–${v.retired_year}`:''}`:'도입 연도 미확인'} · {v.label}</b><p style={{fontSize:11,color:'#71717a',marginTop:3}}>{v.is_current?'현재 제공 중':'이전 수집본'} · {v.version_kind==='brand_redesign'?'브랜드 리뉴얼':v.version_kind==='legacy_import'?'기존 자산 등록':'자산 검수·수정'} · {v.review_status==='verified'?'검수 완료':'원본 확인 대기'} · 수집 {new Date(v.observed_at).toLocaleDateString('ko-KR')}</p><div style={{fontSize:11,display:'flex',gap:10,marginTop:5}}>{svg&&<a href={svg} target="_blank" rel="noopener noreferrer">SVG 보기</a>}{png&&<a href={png} target="_blank" rel="noopener noreferrer">PNG 보기</a>}{v.source_url&&<a href={v.source_url} target="_blank" rel="noopener noreferrer">출처</a>}</div></div>{isAdmin&&<button type="button" onClick={()=>setEditing({...v})} style={{fontSize:11}}>연도·출처 관리</button>}</article>;})}</div>}
 {isAdmin&&editing&&<div style={{marginTop:14,padding:12,background:'#f8f7ff',borderRadius:8,display:'grid',gap:8,fontSize:12}}><label>버전 이름 <input aria-label="버전 이름" value={editing.label} onChange={e=>setEditing({...editing,label:e.target.value})}/></label><label>도입 연도 <input aria-label="도입 연도" type="number" min={1} max={new Date().getFullYear()} value={editing.introduced_year??''} onChange={e=>setEditing({...editing,introduced_year:e.target.value?Number(e.target.value):null})}/></label><label>종료 연도 <input aria-label="종료 연도" type="number" min={1} max={new Date().getFullYear()} value={editing.retired_year??''} onChange={e=>setEditing({...editing,retired_year:e.target.value?Number(e.target.value):null})}/></label><label>이력 구분 <select value={editing.version_kind} onChange={e=>setEditing({...editing,version_kind:e.target.value})}><option value="legacy_import">기존 자산 등록</option><option value="asset_revision">자산 검수·수정</option><option value="brand_redesign">브랜드 리뉴얼</option></select></label><label>근거 출처 <input aria-label="연도 근거 출처" type="url" value={editing.source_url||''} onChange={e=>setEditing({...editing,source_url:e.target.value})}/></label><label>검수 메모 <textarea value={editing.source_note||''} onChange={e=>setEditing({...editing,source_note:e.target.value})}/></label><p style={{color:'#71717a',fontSize:11}}>확인되지 않은 연도는 비워 주세요. 연도를 기록할 때는 출처가 필요해요.</p><div><button disabled={saving} onClick={()=>void save()}>{saving?'저장 중…':'이력 저장하기'}</button> <button onClick={()=>setEditing(null)}>취소</button></div></div>}
 </details></section>;
}
